- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-scenario001
      - puppet-openstack-integration-jobs-scenario004
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-ceph-unit-6.28-ubuntu-focal-zed
    gate:
      jobs:
        - puppet-ceph-unit-6.28-ubuntu-focal-zed

# NOTE(tkajinam): stable/zed supports Ubuntu 20.04 and Puppet 6
- job:
    name: puppet-ceph-unit-6.28-ubuntu-focal-zed
    parent: puppet-openstack-unit-base
    nodeset: ubuntu-focal
    override-checkout: stable/zed
    vars:
      puppet_gem_version: 6.28.0
      rspec_puppet_version: '= 2.9.0'
